# Generated by Django 3.1.3 on 2020-11-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isloggedin',
            field=models.BooleanField(default=False),
        ),
    ]
