# Generated by Django 3.1.3 on 2020-11-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebProject', '0005_auto_20201114_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='likedBy',
            field=models.ManyToManyField(blank=True, related_name='likedArticles', to='WebProject.Users'),
        ),
    ]
